In [194]:
import pandas as pd
df_customer=pd.read_csv('03_Customer_Behavior_Data_THPT.csv')
df_item=pd.read_csv('03_Item_information_Data_THPT.csv')
df_shelf=pd.read_csv('03_Shelf_Information_Data_THPT.csv')
# df_temp = pd.merge(df1, df2, on='Shelf ID', how='inner')
# df_master = pd.merge(df_temp, df3, on='Shelf ID', how='inner')
# print(df_master['Item ID_x'].unique())
# print(df_master['Item ID_y'].unique())
# print(df_master.columns)
# print(df_master.head())

# Code df_master bi merge sai 

print(f'Customer cols {df_customer.columns} and lens are {len(df_customer)}')
print(f'Item cols {df_item.columns} and lens are {len(df_item)}')
print(f'Shelf cols {df_shelf.columns} and lens are {len(df_shelf)}')

Customer cols Index(['Shelf ID', 'Person ID', 'Date', 'Time', 'Day', 'Age', 'Gender',
       'Height', 'Weight', 'Married status', 'Item ID', 'Looking at item (s)',
       'Holding the item (s)', 'Holding the bag', 'Picking up item',
       'Returning item', 'Putting item into bag', 'Taking item out of bag',
       'Putting item into bag in the 2nd time'],
      dtype='object') and lens are 15394
Item cols Index(['Shelf ID', 'Item ID', 'Name', 'Origin', 'Price', 'Marketing strategy',
       'Discount ', 'Rate'],
      dtype='object') and lens are 134
Shelf cols Index(['Shelf ID', 'Description', 'Width', 'Height', 'Length',
       'Number of items', 'Shape'],
      dtype='object') and lens are 8

In [195]:
df_temp = pd.merge(df_customer, df_item, on=['Shelf ID','Item ID'], how='inner')
df_full = pd.merge(df_temp, df_shelf, on=['Shelf ID'], how='inner')
df_full

,Shelf ID,Person ID,Date,Time,Day,Age,Gender,Height_x,Weight,Married status,...,Price,Marketing strategy,Discount,Rate,Description,Width,Height_y,Length,Number of items,Shape
0,4,1,2024-07-06,10:00:00,Saturday,52,Female,162,41,Married,...,"28,500 ₫",False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng
1,4,23,2024-07-06,13:12:00,Saturday,65,Male,171,69,Married,...,"28,500 ₫",False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng
2,4,35,2024-07-06,15:47:00,Saturday,70,Male,171,78,Married,...,"28,500 ₫",False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng
3,4,39,2024-07-06,16:10:00,Saturday,51,Female,147,45,Married,...,"28,500 ₫",False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng
4,4,114,2024-07-06,0:30:00,Saturday,46,Male,169,75,Married,...,"28,500 ₫",False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15389,6,1367,2024-07-05,12:53:00,Friday,34,Male,169,59,Single,...,"300,000 ₫",False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng
15390,6,1417,2024-07-05,18:35:00,Friday,30,Female,166,46,Single,...,"300,000 ₫",False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng
15391,6,1455,2024-07-05,23:02:00,Friday,49,Male,175,66,Single,...,"300,000 ₫",False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng
15392,6,1460,2024-07-05,0:02:00,Friday,23,Male,175,68,Single,...,"300,000 ₫",False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng
15393,6,1473,2024-07-05,1:18:00,Friday,29,Male,177,77,Single,...,"300,000 ₫",False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng

In [196]:
df_full['Price'] = df_full['Price'].str.replace('₫', '', regex=False)  # Remove the currency symbol
df_full['Price'] = df_full['Price'].str.replace(',', '', regex=False)  # Remove commas
df_full['Price'] = df_full['Price'].astype(float)

In [197]:
print(len(df_full.groupby('Name').filter(lambda x: x['Item ID'].nunique() > 1)))

0

In [198]:
print(df_full.columns)

Index(['Shelf ID', 'Person ID', 'Date', 'Time', 'Day', 'Age', 'Gender',
       'Height_x', 'Weight', 'Married status', 'Item ID',
       'Looking at item (s)', 'Holding the item (s)', 'Holding the bag',
       'Picking up item', 'Returning item', 'Putting item into bag',
       'Taking item out of bag', 'Putting item into bag in the 2nd time',
       'Name', 'Origin', 'Price', 'Marketing strategy', 'Discount ', 'Rate',
       'Description', 'Width', 'Height_y', 'Length', 'Number of items',
       'Shape'],
      dtype='object')

In [25]:
df_temp.columns

Index(['Shelf ID', 'Person ID', 'Date', 'Time', 'Day', 'Age', 'Gender',
       'Height', 'Weight', 'Married status', 'Item ID', 'Looking at item (s)',
       'Holding the item (s)', 'Holding the bag', 'Picking up item',
       'Returning item', 'Putting item into bag', 'Taking item out of bag',
       'Putting item into bag in the 2nd time', 'total time (s)', 'Name',
       'Origin', 'Price', 'Marketing strategy', 'Discount ', 'Rate'],
      dtype='object')

In [199]:
#câu hỏi 1: Thống kê 5 mặt hàng với lượng khách hàng nhìn thấy nhiều nhất

group_looked = df_full.groupby('Name')['Looking at item (s)'].sum().reset_index(name='Tổng lượt nhìn')
top_5_items_looked = group_looked.sort_values(by='Tổng lượt nhìn', ascending=False).head(5)
print(top_5_items_looked)

                     Name  Tổng lượt nhìn
108   Sữa chua uống Probi           11503
109  Sữa chua uống Yakult           11454
110           Sữa ông thọ            7712
4           Bim bim Oishi            7415
77   Snack khoai tây Lays            7051

In [200]:
#câu hỏi 2: Thống kê 5 mặt hàng có tổng thời gian nhìn và cầm xem lâu nhất
df_full['total time (s)']=df_full['Looking at item (s)'] + df_full['Holding the item (s)']
grouped = df_full.groupby('Name')['total time (s)'].sum().reset_index(name='total (s)')
top_5_items = grouped.sort_values(by='total (s)', ascending=False).head(5)
print(top_5_items)

                     Name  total (s)
108   Sữa chua uống Probi      22896
109  Sữa chua uống Yakult      22896
110           Sữa ông thọ      13939
4           Bim bim Oishi      13866
77   Snack khoai tây Lays      13362

In [201]:
#câu hỏi 3: Thống kê 5 mặt hàng được mua nhiều nhất

df_full_buy = df_full[(df_full['Putting item into bag']==True)&(df_full['Taking item out of bag']==False)]
df_full_buy.groupby(['Name']).size().sort_values(ascending=False).head(5)

Name
Kem tràng tiền                              159
Lốc 4 hộp sữa tươi ít đường TH true MILK    159
Sữa bột Milo                                158
Bánh trứng Custard                          156
Dầu gội Romano                               99
dtype: int64

In [136]:
df_full.columns

Index(['Shelf ID', 'Person ID', 'Date', 'Time', 'Day', 'Age', 'Gender',
       'Height_x', 'Weight', 'Married status', 'Item ID',
       'Looking at item (s)', 'Holding the item (s)', 'Holding the bag',
       'Picking up item', 'Returning item', 'Putting item into bag',
       'Taking item out of bag', 'Putting item into bag in the 2nd time',
       'Name', 'Origin', 'Price', 'Marketing strategy', 'Discount ', 'Rate',
       'Description', 'Width', 'Height_y', 'Length', 'Number of items',
       'Shape', 'total time (s)'],
      dtype='object')

Name
Kem tràng tiền                              159
Lốc 4 hộp sữa tươi ít đường TH true MILK    159
Sữa bột Milo                                158
Bánh trứng Custard                          156
Dầu gội Romano                               99
dtype: int64

In [202]:
#câu hỏi 4: Thống kê 5 mặt hàng thường được cầm lên rồi trả lại nhiều nhất



df_full_filter_q4 = df_full[(df_full['Picking up item'] == True) & (df_full['Returning item'] == True)]
df_full_filter_q4.groupby('Name').size().sort_values(ascending=False).head(5)

Name
4 hộp sữa lúa mạch Milo 180ml    134
Snack khoai tây Lays             127
Mý ý SG Food                     117
Nước lẩu Barona                  116
Bánh Chocopie                    114
dtype: int64

In [9]:
#câu hỏi 5: Các nhóm khách hàng theo độ tuổi (Thiếu niên: 18 - 30; Trung niên: 31 - 60; Cao tuổi: > 60) mua mặt hàng nào nhiều nhất?

   Item ID_x  Thiếu niên
1          1        4025
   Item ID_x  Trung niên
7          7        8260
   Item ID_x  Cao tuổi
8          8      4526

In [203]:
df_buy_filter_thieunien = df_full_buy[(df_full_buy['Age'] >= 18) & (df_full_buy['Age'] <= 30)].copy()
df_buy_filter_thieunien.groupby('Name').size().sort_values(ascending=False).head(1)

Name
Bánh trứng Custard    42
dtype: int64

In [204]:
df_buy_filter_trungnien = df_full_buy[(df_full_buy['Age']>=31) & (df_full_buy['Age']<=60)].copy()
df_buy_filter_trungnien.groupby('Name').size().sort_values(ascending=False).head(1)

Name
Kem tràng tiền    89
dtype: int64

In [205]:
df_buy_filter_caotuoi = df_full_buy[df_full_buy['Age']>60].copy()
df_buy_filter_caotuoi.groupby('Name').size().sort_values(ascending=False).head(1)

Name
Sữa bột Milo    49
dtype: int64

In [10]:
#câu hỏi 6: Ngày nào trong tuần có doanh thu cao nhất?
# grouped = df_master.groupby('Day')['Item ID_x'].sum().reset_index(name='item_quantity')
# top_1_items = grouped.sort_values(by='item_quantity', ascending=False).head(1)
# print(top_1_items)

# Sai vi phai tinh doanh thu ko phai so luong, item quantity ko phai la so luong mua 

# doanh thu = price * 1

        Day  item_quantity
2  Saturday         618017

In [97]:

df_full

,Shelf ID,Person ID,Date,Time,Day,Age,Gender,Height_x,Weight,Married status,...,Marketing strategy,Discount,Rate,Description,Width,Height_y,Length,Number of items,Shape,total time (s)
0,4,1,2024-07-06,10:00:00,Saturday,52,Female,162,41,Married,...,False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng,63
1,4,23,2024-07-06,13:12:00,Saturday,65,Male,171,69,Married,...,False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng,51
2,4,35,2024-07-06,15:47:00,Saturday,70,Male,171,78,Married,...,False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng,56
3,4,39,2024-07-06,16:10:00,Saturday,51,Female,147,45,Married,...,False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng,60
4,4,114,2024-07-06,0:30:00,Saturday,46,Male,169,75,Married,...,False,10,3,Quầy gia vị,500,180,100,19,Kệ hàng,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15389,6,1367,2024-07-05,12:53:00,Friday,34,Male,169,59,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,13
15390,6,1417,2024-07-05,18:35:00,Friday,30,Female,166,46,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,38
15391,6,1455,2024-07-05,23:02:00,Friday,49,Male,175,66,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,23
15392,6,1460,2024-07-05,0:02:00,Friday,23,Male,175,68,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,10
15393,6,1473,2024-07-05,1:18:00,Friday,29,Male,177,77,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,45

In [206]:
df_full_buy.groupby('Day')['Price'].sum().sort_values(ascending=False)

Day
Saturday     192021600.0
Sunday       184134400.0
Tuesday       55067600.0
Thursday      51941300.0
Friday        50958000.0
Wednesday     42968200.0
Monday        39364600.0
Name: Price, dtype: float64

In [207]:
#câu hỏi 7: Trong 3 nhóm tuổi sau: Thiếu niên (18 - 30),  Trung niên (31 - 60), Cao tuổi: (> 60),  nhóm tuổi nào có số người đi siêu thị nhiều nhất?


df_full_filter_thieunien = df_full[(df_full['Age'] >= 18) & (df_full['Age'] <= 30)].copy()
df_full_filter_trungnien = df_full[(df_full['Age']>=31) & (df_full['Age']<=60)].copy()
df_full_filter_caotuoi = df_full[df_full['Age']>60].copy()

In [208]:
print(f"So nguoi di sieu thi cua nhom thieu nien la {df_full_filter_thieunien['Person ID'].nunique()}, trung nien la {df_full_filter_trungnien['Person ID'].nunique()}, cao tuoi la {df_full_filter_caotuoi['Person ID'].nunique()}")

So nguoi di sieu thi cua nhom thieu nien la 339, trung nien la 753, cao tuoi la 408

In [209]:
#câu hỏi 8: Top 5 các mặt hàng giảm giá được người dùng mua nhiều nhất?
df_full_buy[df_full_buy['Discount ']>0].groupby('Name').size().sort_values(ascending=False).head(5)

Name
Kem tràng tiền        159
Sữa bột Milo          158
Bánh trứng Custard    156
Dầu gội Romano         99
Khăn tắm Shine         94
dtype: int64

In [210]:
#câu hỏi 9: Top 3 quầy hàng nào có lượt cầm xem nhiều nhất?
group_holding = df_full.groupby('Shelf ID')['Holding the item (s)'].sum().reset_index(name='Tổng lượt cầm xem')
top_3_sections_holding = group_holding.sort_values(by='Tổng lượt cầm xem', ascending=False).head(3)
print(top_3_sections_holding)

   Shelf ID  Tổng lượt cầm xem
7         7             100194
0         0              74955
1         1              58668

In [ ]:
#câu hỏi 10: Trong số các sản phẩm được đánh giá cao nhất, top 3 sản phẩm nào được mua nhiều nhất?
df_full_buy[(df_full_buy['Rate']==5)].groupby('Name').size().sort_values(ascending=False).head(3)

   Item ID_y  Total_Purchases
0          0             3216
5          6             2705
8         10             2414

In [19]:
#câu hỏi 11: Câu hỏi mở: Tìm ra mặt hàng hay được chú ý nhất của những nhóm khách hàng cụ thể
# groups = ['Thiếu niên', 'Trung niên', 'Cao tuổi']
# for group in groups:
#     grouped = df_master.groupby([group, 'Name'])['Looking at item (s)'].sum().reset_index(name='Total_Time_Looked')
#     top_item_per_group = grouped.loc[grouped.groupby(group)['Total_Time_Looked'].idxmax()]
#     print(f"Mặt hàng được chú ý nhất trong nhóm: {group}")
#     print(top_item_per_group[['Name', 'Total_Time_Looked']])

Mặt hàng được chú ý nhất trong nhóm: Thiếu niên
             Name  Total_Time_Looked
3    Bibigo Mandu              78394
137  Bibigo Mandu              23050
Mặt hàng được chú ý nhất trong nhóm: Trung niên
             Name  Total_Time_Looked
3    Bibigo Mandu              51259
137  Bibigo Mandu              50185
Mặt hàng được chú ý nhất trong nhóm: Cao tuổi
             Name  Total_Time_Looked
3    Bibigo Mandu              73235
137  Bibigo Mandu              28209

Thoi gian chu y = Thoi gian looking + thoi gian holding (Khi chu y 1 san pham nguoi dung se co 2 thao tac hoac la nhin no hoac la cam nam no)

San pham chu y : Thoi gian chu y > 30 hoac Nguoi do picking up the item (nho giai thich vi sao tinh chat nay goi la chu y)

In [134]:
cond_thieunien = (df_full_filter_thieunien['Looking at item (s)'] + df_full_filter_thieunien['Holding the item (s)']  > 30) | (df_full_filter_thieunien['Picking up item']==True)

cond_trungnien = (df_full_filter_trungnien['Looking at item (s)'] + df_full_filter_trungnien['Holding the item (s)']  > 30) | (df_full_filter_trungnien['Picking up item']==True)

cond_caotuoi = (df_full_filter_caotuoi['Looking at item (s)'] + df_full_filter_caotuoi['Holding the item (s)']  > 30) | (df_full_filter_caotuoi['Picking up item']==True)


print(f" Top mat hang thieu nien la {df_full_filter_thieunien[cond_thieunien].groupby('Name').size().sort_values(ascending=False).head(10).index.tolist()}")
print(f" Top mat hang trung nien la {df_full_filter_trungnien[cond_trungnien].groupby('Name').size().sort_values(ascending=False).head(10).index.tolist()}")
print(f" Top mat hang cao tuoi la {df_full_filter_caotuoi[cond_caotuoi].groupby('Name').size().sort_values(ascending=False).head(10).index.tolist()}")

 Top mat hang thieu nien la ['Sữa bột Anmum Materna', 'Bánh Chocopie', 'Snack khoai tây Lays', 'Kẹo cao su Cool Air Fresh', 'Bánh trứng Custard', 'Bim bim Oishi', 'Lốc 4 hộp sữa tươi ít đường TH true MILK', '4 hộp sữa lúa mạch Milo 180ml', 'Viên thả lẩu cầu tre', 'Nước lẩu Barona']
 Top mat hang trung nien la ['Sữa ông thọ', 'Snack khoai tây Lays', 'Kem tràng tiền', '4 hộp sữa lúa mạch Milo 180ml', 'Thạch rau câu Đức Hạnh', 'Sữa chua uống Probi', 'Sữa chua Vinamik', 'Thanh cua Akira', 'Hạt hướng dương Chacheer', 'Sữa bột Ensure Gold lúa mạch']
 Top mat hang cao tuoi la ['Bánh trứng Custard', 'Xúc xích CP', 'Bibigo Mandu', 'Kẹo dẻo Alphelibe', 'Sữa bột Milo', 'Sửa chua TH', 'Bim bim Oishi', 'Hạt hướng dương Chacheer', 'Bánh Chocopie', 'Sữa chua Susu']

In [20]:
#câu hỏi 12: Câu hỏi mở: Có những mặt hàng nào cần được sắp xếp lại trong cửa hàng không? Tại sao?
# Tính tổng thời gian chú ý cho tất cả các mặt hàng trong từng nhóm khách hàng
total_attention = df_master.groupby('Name')['Looking at item (s)'].sum().reset_index(name='Total_Time_Looked')

# Xác định ngưỡng thời gian chú ý thấp (ví dụ, thời gian chú ý thấp hơn 25% của tổng thời gian)
threshold = total_attention['Total_Time_Looked'].quantile(0.25)

# Lọc ra các mặt hàng có tổng thời gian chú ý thấp hơn ngưỡng
items_to_rearrange = total_attention[total_attention['Total_Time_Looked'] < threshold]

# Hiển thị danh sách các mặt hàng cần sắp xếp lại
print("Những mặt hàng có thời gian chú ý thấp cần sắp xếp lại:")
print(items_to_rearrange[['Name', 'Total_Time_Looked']])

# Kiểm tra sự chú ý không đồng đều giữa các nhóm khách hàng
for group in groups:
    group_attention = df_master.groupby([group, 'Name'])['Looking at item (s)'].sum().reset_index(name='Total_Time_Looked')
    print(f"Mặt hàng trong nhóm {group} có thời gian chú ý thấp:")
    print(group_attention[group_attention['Total_Time_Looked'] < threshold])

Những mặt hàng có thời gian chú ý thấp cần sắp xếp lại:
                                              Name  Total_Time_Looked
15                             Bếp nướng Lock&Lock              24391
16                              Bếp nướng Sunhouse              24391
17                           Bếp điện từ Lock&Lock              24391
18                            Bếp điện từ Sunhouse              24391
20                                  Chảo Lock&Lock              24391
21                                   Chảo Sunhouse              24391
34                                   Gấu bông Miyu              23008
48                           Máy xay sinh tố Comet              24391
49                       Máy xay sinh tố Lock&Lock              24391
50                        Máy xay sinh tố Sunhouse              24391
67                            Nồi cơm điện Cuckcoo              24391
68                           Nồi cơm điện Kangaroo              24391
69                          Nồi cơm điện Lock&Lock              24391
70                           Nồi cơm điện Sunhouse              24391
71                       Phích cắm điện Ðiện Quang              24391
76                                Siêu nhân Marvel              23008
81   Sách - Nuôi Con không phải là cuộc chiến Easy              23008
82                          Sách Bên Nhau Trọn Ðời              23008
83                 Sách Chào con Ba mẹ đã sẵn sàng              23008
84                          Sách Công Tắc Tình Yêu              23008
85              Sách Cẩm Nang Mang Thai & Sinh con              23008
86                                Sách Nhà Giả Kim              23008
87                      Sách Thám tử Sherlock Home              23008
88                        Sách Thép Ðã Tôi Thế Ðây              23008
89           Sách cho trẻ sơ sinh đến 6 tháng tuổi              23008
90                        Sách cho trẻ từ 1-2 tuổi              23008
91                        Sách cho trẻ từ 2-3 tuổi              23008
92                        Sách cho trẻ từ 4-5 tuổi              23008
93                                   Sách Ðạo Tình              23008
94                               Sách Ðắc Nhẫn Tâm              23008
113                                Truyện Doraemon              23008
114                             Truyện tranh Conan              23008
128                             Ðèn bàn Ðiện Quang              24391
133                                Ổ cắm điện Lioa              24391
Mặt hàng trong nhóm Thiếu niên có thời gian chú ý thấp:
     Thiếu niên                   Name  Total_Time_Looked
15        False    Bếp nướng Lock&Lock              18244
16        False     Bếp nướng Sunhouse              18244
17        False  Bếp điện từ Lock&Lock              18244
18        False   Bếp điện từ Sunhouse              18244
20        False         Chảo Lock&Lock              18244
..          ...                    ...                ...
263        True   Ðường kính Toàn Phát              12051
264        True    Ðường phèn Biên Hoà              12051
265        True               Ðậu xanh               8678
266        True                 Ðậu đỏ               8678
267        True        Ổ cắm điện Lioa               6147

[168 rows x 3 columns]
Mặt hàng trong nhóm Trung niên có thời gian chú ý thấp:
     Trung niên                           Name  Total_Time_Looked
0         False  4 hộp sữa lúa mạch Milo 180ml              26611
1         False                        Bia 333              20536
2         False            Bia Sài Gòn Special              20536
11        False                  Bánh đa Vifon              20536
15        False            Bếp nướng Lock&Lock              12518
..          ...                            ...                ...
258        True                   Vodka Hà Nội              20153
262        True             Ðèn bàn Ðiện Quang              11873
265        True                       Ðậu xanh              20153
266        True                         Ðậu đỏ              20153
267        True                Ổ cắm điện Lioa              11873

[173 rows x 3 columns]
Mặt hàng trong nhóm Cao tuổi có thời gian chú ý thấp:
     Cao tuổi                   Name  Total_Time_Looked
15      False    Bếp nướng Lock&Lock              18020
16      False     Bếp nướng Sunhouse              18020
17      False  Bếp điện từ Lock&Lock              18020
18      False   Bếp điện từ Sunhouse              18020
20      False         Chảo Lock&Lock              18020
..        ...                    ...                ...
263      True   Ðường kính Toàn Phát              13583
264      True    Ðường phèn Biên Hoà              13583
265      True               Ðậu xanh              11858
266      True                 Ðậu đỏ              11858
267      True        Ổ cắm điện Lioa               6371

[168 rows x 3 columns]

In [135]:
df_full[(df_full['Holding the item (s)']==0)]

,Shelf ID,Person ID,Date,Time,Day,Age,Gender,Height_x,Weight,Married status,...,Marketing strategy,Discount,Rate,Description,Width,Height_y,Length,Number of items,Shape,total time (s)
10176,1,22,2024-07-06,13:10:00,Saturday,46,Female,162,51,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,7
10193,1,213,2024-07-06,12:02:00,Saturday,73,Male,173,80,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,4
10205,1,308,2024-07-06,22:53:00,Saturday,36,Female,152,56,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,5
10209,1,330,2024-07-06,2:05:00,Saturday,63,Female,164,49,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,14
10218,1,462,2024-07-07,11:47:00,Sunday,62,Male,168,68,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,13
10239,1,564,2024-07-07,0:40:00,Sunday,67,Female,165,55,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,6
10249,1,714,2024-07-07,17:52:00,Sunday,20,Female,148,48,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,6
10261,1,953,2024-07-02,10:30:00,Tuesday,28,Female,155,52,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,12
10274,1,1180,2024-07-03,22:59:00,Wednesday,28,Female,163,43,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,9
10286,1,1301,2024-07-04,23:10:00,Thursday,46,Male,177,85,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,8
10288,1,1362,2024-07-05,12:22:00,Friday,70,Female,160,42,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,11
12006,1,79,2024-07-06,20:22:00,Saturday,51,Female,148,57,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,13
12033,1,338,2024-07-06,2:54:00,Saturday,36,Male,168,55,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,14
12044,1,517,2024-07-07,18:51:00,Sunday,21,Male,178,70,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,12
12045,1,517,2024-07-07,19:13:00,Sunday,21,Male,178,70,Single,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,7
12088,1,1046,2024-07-02,22:14:00,Tuesday,46,Male,179,66,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,10
12089,1,1051,2024-07-02,22:17:00,Tuesday,53,Female,150,54,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,4
12097,1,1174,2024-07-03,21:58:00,Wednesday,40,Male,173,87,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,14
12127,1,1419,2024-07-05,18:26:00,Friday,54,Female,155,53,Married,...,False,0,3,Quầy hoá mỹ phẩm,100,180,400,18,Kệ hàng,10
14312,6,221,2024-07-06,12:52:00,Saturday,31,Male,177,81,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,27
14350,6,97,2024-07-06,22:00:00,Saturday,49,Female,148,59,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,37
14370,6,341,2024-07-06,3:22:00,Saturday,58,Male,177,70,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,16
14500,6,31,2024-07-06,14:21:00,Saturday,48,Female,148,49,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,20
14538,6,1071,2024-07-02,0:53:00,Tuesday,57,Female,147,40,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,15
14584,6,758,2024-07-07,23:33:00,Sunday,38,Female,150,53,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,26
14590,6,1013,2024-07-02,17:35:00,Tuesday,36,Male,175,60,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,24
14595,6,1183,2024-07-03,23:03:00,Wednesday,68,Female,159,48,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,15
14620,6,285,2024-07-06,20:19:00,Saturday,73,Female,154,40,Married,...,False,0,5,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,31
14659,6,1126,2024-07-03,15:52:00,Wednesday,62,Female,162,49,Married,...,False,0,5,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,24
14769,6,807,2024-07-07,4:03:00,Sunday,33,Female,152,58,Single,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,34
14810,6,506,2024-07-07,17:25:00,Sunday,41,Female,150,42,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,24
14824,6,772,2024-07-07,0:44:00,Sunday,18,Female,159,50,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,22
14871,6,506,2024-07-07,17:32:00,Sunday,41,Female,150,42,Single,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,26
14987,6,548,2024-07-07,22:16:00,Sunday,51,Female,149,42,Married,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,31
15157,6,1144,2024-07-03,18:02:00,Wednesday,22,Female,164,48,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,32
15281,6,1363,2024-07-05,12:13:00,Friday,67,Male,168,89,Married,...,False,0,4,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,68
15296,6,273,2024-07-06,19:23:00,Saturday,32,Female,166,59,Single,...,False,0,3,Quầy sách và đồ chơi,100,180,600,16,Kệ hàng,31

- Thế nào là mặt hàng cần được sắp xếp lại ?

    - Trong ngữ cảnh này, cần sắp xếp lại ko có nghĩa là món hàng đó lộn xộn

    - Hiểu đúng hơn là cần sắp xếp vị trí để thu hút đc nhiều người hơn 

- Tiêu chuẩn nào để chọn ra được mặt hàng được sắp xếp lại 

    - Tìm nx mặt hàng mà có thời gian chú ý thấp (lấy top 10 thap nhat của tổng thời gian chú ý của tất cả các mặt hàng )

    <!-- - Tim nx mat hang không hoặc ít được mua (lấy top10 ) (df_buy) -->